### ISSUE TITLE
Some tricky variable names, too few skeleton functions, other possible bonuses

### ISSUE THREAD

**Issue by rrcobb** [learn-co-curriculum/apis-and-iteration#6]
No tests make this lab more open-ended and harder by default, but there also seem to be some poorly-named variables and not enough / the wrong functions in the skeleton. It could be good that this lab stretches students skills in some way, but I've seen lots of students get stuck somewhere in the giant function of this lab, so I have a sense that maybe we are introducing too much difficulty at once.

I think some helpful changes to variable/method names might be:
- `character` => `character name` in the prompt in command_line_interface.rb:6, 
- `all_characters` => `json_response` on api_communicator:7
- `character_hash` => `response_as_hash` on api_communicator.rb:8
- `films_hash` => `film_hashes_array` on api_communicator:26
- `parse_character_movies` => `print_movies` on api_communicator:21

It could be part of the challenge that there are too few methods in the skeleton as written, but IMHO it would be nicer if there were more bite-sized pieces to tackle. The 'bonus' is to break the big method that does all the work into smaller, reusable functions. I'm not quite sure that students are ready for that on their own at this point - it might be better to help them learn by giving them a skeleton of small functions to begin with.

Another bonus that I found that I frequently assigned to students who completed this lab: handling errors nicely when a character didn't exist in the result from the api. (Some students even took this a step further, saw that their results had a `"next"` key, and fetched all the pages of characters so that they _knew_ they weren't missing any. Other students did all the character and film fetching up front, so that the CLI was faster when the user actually responded to the prompt.

I can PR into this lab with updates if those changes make sense (updating variable names, breaking out a couple more skeleton functions to help break the problem down, update the BONUS to mention these other ideas)

**Comment by realAndrewCohn** [comment]
Hey @rrcobb can you submit a PR. I think this will also address #7. Can you tag me as a reviewer? Thanks!

![bitmoji](https://render.bitstrips.com/v2/cpanel/3e85117a-d59b-4726-b63d-987594b4bfd7-7c243825-53cb-4c20-a7d9-3fc8d332e86d-v1.png?transparent=1&palette=1&width=246)

**Comment by Joshua-Miles** [comment]
Hi @realAndrewCohn , my name is Joshua, I'm a new technical coaching fellow in Houston. I think I've fixed a few of these issues in a recent pull request; I'm sorry if I've over stepped, but we used this lab, I saw these issues and thought I would try to help if I could. Please let me know if you would prefer I refrain from such actions in the future, or if there is a better way of going about this. Thank you so much!

**Comment by realAndrewCohn** [comment]
@rrcobb does #8 address enough of the issues in this lab? Are we good to close this issue?
